### PR TITLE
makes the cross under the search button functional #49

### PR DESCRIPTION
**Pull request by Shinchan3102**

### CODE REVIEW

**Comment by AnkitaMalik22** [comment]
Can you explain what changes you've made? I didn't understand

**Comment by Shinchan3102** [comment]
yep after selecting an option when one wants to cut it through the cross inside the search button then it does nothing, i just make it functional

**Comment by Shinchan3102** [comment]
or if you think about anything else , just tell me i will try it

**Comment by AnkitaMalik22** [comment]
> or if you think about anything else , just tell me i will try it

Okay !

**Pull request merged**
