### PR TITLE
added some styling for the tablet design #46

### LINKED ISSUE #46: Style the Ui to look more aesthestic for tablet device
I would like to style the UI to make it appear more appealing on tablet device insetad of have a long box with it's content aligned to one side

### PR DESCRIPTION
**Pull request by Ericchuk**
close #46

I have added some styling to the home.module.css file, this styles helps make the card appear more clean on tablet and reduce scroll. 
During the course of doing it I also modified the profileCard by adding section to it, so as to keep things in place.

### CODE REVIEW

**Comment by AnkitaMalik22** [comment]
> close #46
> 
> I have added some styling to the home.module.css file, this styles helps make the card appear more clean on tablet and reduce scroll. 
> During the course of doing it I also modified the profileCard by adding section to it, so as to keep things in place.

It's creating problem in mobile
Fix the profile containers



The title & subtitle is not in the centre

**Comment by Ericchuk** [comment]
it is centered on my own screen

**Comment by Ericchuk** [comment]
will work on it

**Comment by AnkitaMalik22** [comment]
Thanks for contributing!

**Pull request merged**
