### PR TITLE
removing same text

### PR DESCRIPTION
**Pull request by smiti-maheshwari**
Was checking the UI and saw this issue - https://github.com/AnkitaMalik22/devmate/issues/2. I have a suggestion that the  text which is used twice "Find Your DEV Mate!" can be removed from the UI once and "search text!" can have "..." instead of "!". The UI with the changes can be see here:

Screenshot 2022-10-12 at 12 16 20 AM

Kindly review the changes and let me know if they seem fine. Excited to see the repo in [Hacktoberfest2022](https://github.com/topics/hacktoberfest) discord. :)

### CODE REVIEW

**Comment by AnkitaMalik22** [comment]
can you replace "Find Your DEV Mate!" subtitle with something else without just removing it?

**Comment by smiti-maheshwari** [comment]
Would this be better - "search your Mates now ..."? Also, I see that your app is not listed in hacktoberfest. Can that happen?

**Comment by AnkitaMalik22** [comment]
> 

it's showing now! thanks &"search your Mates now ..."? is good you can add

**Comment by smiti-maheshwari** [comment]
@AnkitaMalik22 it looks like this now: 
Screenshot 2022-10-12 at 12 44 33 PM

**Comment by AnkitaMalik22** [comment]
thanks for contributing!

**Pull request merged**
