### PR TITLE
added typewriter effect fot the "Searching your mate" part

### PR DESCRIPTION
**Pull request by riya461**
The small change is made in the index.js and css file., Its just basic typewriter effect that looks nice.

### CODE REVIEW

**Comment by AnkitaMalik22** [comment]
Can you try this typewriter effect  using Javascript?

**Comment by AnkitaMalik22** [comment]
Screenshot_20221015-224452
The site isn't looking good after this.you can remove the white background and see

**Comment by riya461** [comment]
Is this the issue only while using in mobile or does the same issue happen while using desktop too ? I can try using js

**Comment by riya461** [comment]
image
is this better now ?

**Comment by AnkitaMalik22** [comment]
> image
> is this better now ?

It's typewriting only once after loading the page.
Something like this - [](https://codepen.io/hi-im-si/pen/ALgzqo)

**Comment by riya461** [comment]
I cant find that page 
But I have made a continuous typewriting style now.
Let me know if there is any changes to be made!

**Pull request closed without merging**
