### PR TITLE
Fix :Profile Cards- Make it responsive [fixes #17]

### LINKED ISSUE #17: Make it responsive
The profile cards aren't responsive

### PR DESCRIPTION
**Pull request by najeebkp**
### Fix :Profile Cards- Make it responsive [fixes #17]

### CODE REVIEW

**Review by soumdatta81 — APPROVED** [review]

**Comment by AnkitaMalik22** [comment]
Screenshot_20221012-165943
Can you reduce the width for mob devices ?

**Review by soumdatta81 — CHANGES_REQUESTED** [review]
Reduce the width for mobile devices.

**Comment by najeebkp** [comment]
Done !

**Comment by AnkitaMalik22** [comment]
Thanks for Contributing!💙

**Pull request merged**
