### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by codemaniac-sahil**
Added favicon

### CODE REVIEW

**Review by soumdatta81 — COMMENTED** [review]
I noticed that the favicon is blurry. Can it be fixed?

**Comment by codemaniac-sahil** [comment]
yes @soumdatta81, I am working on it.

**Comment by codemaniac-sahil** [comment]
Would please check @soumdatta81 now

**Comment by codemaniac-sahil** [comment]
Now I think It is fixed.

**Comment by codemaniac-sahil** [comment]
Thank you @soumdatta81 for merging my PR.

**Comment by codemaniac-sahil** [comment]
Happy hacktoberfest @soumdatta81

**Pull request merged**
